apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpress.dbHost }}
  WORDPRESS_DB_USER: {{ .Values.wordpress.dbUser }}
  WORDPRESS_DB_NAME: {{ .Values.wordpress.dbName }}