---
- name: Deploy Docker Compose file to EC2
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Copy Docker Compose file to the remote host
      copy:
        src: docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml

    - name: Run Docker Compose
      command: docker-compose -f /home/ec2-user/docker-compose.yml up -d
      args:
        chdir: /home/ec2-user/
